[WIP]メッセージ送信機能の実装
ryosukemotegi/chat-space pull request #13
Opened 2017-01-07 05:34 UTC by ryosukemotegi

### WHAT
メッセージ送信機能を実装する

### WHY
アプリケーションのメイン機能として必要なため

2017-01-10 03:24 UTC, ryosukemotegi commented
空のメッセージ送信時のエラー画面
![message](https://cloud.githubusercontent.com/assets/24385346/21792787/8de6268a-d72f-11e6-933c-f1814d954389.png)

2017-01-10 03:35 UTC, Maverick1211 commented on app/views/groups/_group.html.haml
> -    %p.chat-group__message *メッセージは後で実装
こちらのコメントアウトは削除してしまっても大丈夫です。

2017-01-10 03:39 UTC, Maverick1211 commented on app/controllers/messages_controller.rb
> +    @messages = Message.includes(:user).where(group_id:params[:group_id])
こちらアソシエーションを使って書きましょう（7行目）

2017-01-10 03:45 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
> +    @messages = Message.includes(:user).where(group_id:params[:group_id])
承知しました！　ご指摘ありがとうございます。
修正いたします！

2017-01-10 04:00 UTC, ryosukemotegi commented on app/views/groups/_group.html.haml
> -    %p.chat-group__message *メッセージは後で実装
コメントありがとうございます！
ファイルの4行めの"*メッセージは後で実装"についてのご指摘でしょうか？
こちらはすでに削除済みです。
もし理解違っていたら、大変お手数ですが改めてコメントをお願いできますでしょうか？

2017-01-10 04:05 UTC, hc070208 commented on app/controllers/messages_controller.rb
> +    @message = Message.create(message_params)
createではなくnewですね

2017-01-10 05:28 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
> +    @message = Message.create(message_params)
ご指摘ありがとうございます！
修正いたします！！

2017-01-10 05:38 UTC, takebnn26 commented on app/controllers/messages_controller.rb
> +    @message = Message.new
こちらをアソシエーションをつかった書き方に直すことで、マージするキーを一つ省略することができます

2017-01-10 05:38 UTC, takebnn26 commented on app/controllers/messages_controller.rb
> +      redirect_to group_messages_path, notice: "メッセージを投稿しました。"
こちらのprefixは引数なしで動くものですか？

2017-01-10 05:38 UTC, takebnn26 commented on app/controllers/messages_controller.rb
> +      redirect_to group_messages_path, alert: "メッセージを入力してください。"
こちらも

2017-01-10 05:38 UTC, takebnn26 commented on app/views/groups/_group.html.haml
>    = link_to group_messages_path(group.id), class: 'chat-group__link' do
こちら引数は.idなしでもidを抽出しています

2017-01-10 05:38 UTC, takebnn26 commented on app/views/groups/_group.html.haml
> +      -if group.messages.present?
こちらモデルのほうで一つのメソッドとして定義してみましょう
ビューに処理を書くのは好ましくないので

2017-01-10 05:38 UTC, takebnn26 commented on app/views/messages/_message.html.haml
> +      =message.created_at
こちらcreate_atで出てくるものをより見やすい形に成形しましょう

2017-01-10 05:38 UTC, takebnn26 commented on app/views/messages/index.html.haml
> +          =f.text_area:body, placeholder: "type a message", rows: "1", id:"message_body"
> f.text_area:body

こちらのf.text_areaと:bodyの間はひとマス空けましょう
それだけどとても見やすいです

2017-01-10 05:54 UTC, ryosukemotegi commented on app/views/messages/index.html.haml
> +          =f.text_area:body, placeholder: "type a message", rows: "1", id:"message_body"
アドバイスありがとうございます！修正して、次回以降も注意します！

2017-01-10 05:54 UTC, ryosukemotegi commented on app/views/groups/_group.html.haml
> +      -if group.messages.present?
承知しました、調べて修正します！

2017-01-10 07:57 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
> +    @message = Message.new
承知しました！　修正してみます！

2017-01-10 08:10 UTC, ryosukemotegi commented on app/views/groups/_group.html.haml
>    = link_to group_messages_path(group.id), class: 'chat-group__link' do
ご指摘ありがとうございます、修正しました！

2017-01-10 08:47 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
> +      redirect_to group_messages_path, alert: "メッセージを入力してください。"
いずれも引数なしで指定したグループのgroup_idを反映して動きました。
改めて書き方を確認して修正します。

2017-01-11 07:58 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
> +      redirect_to group_messages_path, alert: "メッセージを入力してください。"
修正しました！

2017-01-11 07:58 UTC, ryosukemotegi commented on app/views/messages/_message.html.haml
> +      =message.created_at
修正しました！

2017-01-11 08:12 UTC, burabaor commented on app/controllers/messages_controller.rb
> +    end
> redirect_to group_messages_path(@group)
この処理は、message.saveの結果に関係なくするものなので、
条件分岐の外に出してしまった方が繰り返さずにすみコードが綺麗になります！

2017-01-11 08:13 UTC, burabaor commented on app/controllers/messages_controller.rb
before_actionでまとめるの良いですね^^

2017-01-11 08:14 UTC, burabaor commented on app/models/group.rb
> +    end
ここは三項演算子を使ってみるとスッキリしそうです！

2017-01-11 08:15 UTC, burabaor reviewed
もう少しです！
ご確認お願いします^^

2017-01-11 08:30 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
> +    end
なるほど、、、ありがとうございます！　修正してみます！

2017-01-11 09:15 UTC, ryosukemotegi commented on app/models/group.rb
> +    end
アドバイスありがとうございます、三項演算子について調べて使ってみます！

2017-01-11 09:16 UTC, ryosukemotegi commented on app/controllers/messages_controller.rb
ありがとうございます！　
まだまだ抜けはありますが、メンターの皆さんのおかげで意識するようになりました。

2017-01-11 11:48 UTC, madana-i requested changes

2017-01-11 11:48 UTC, DaikiInaba commented on app/controllers/messages_controller.rb
> +    redirect_to group_messages_path(@group)
失敗時はrenderを使用しましょう！

2017-01-11 11:48 UTC, DaikiInaba commented on app/models/group.rb
> +    messages.present? ? messages.last.body : "メッセージがありません"
参考演算子でスッキリとまとめてあって素晴らしいです！
式展開を使用しない場合はシングルクォーテーションを使用するとbetterです！

2017-01-11 11:48 UTC, DaikiInaba commented on app/views/groups/_group.html.haml
>    = link_to group_messages_path(group.id), class: 'chat-group__link' do
こちら修正漏れかコミット漏れですか？

2017-01-11 11:48 UTC, DaikiInaba commented on app/views/messages/index.html.haml
> +      =form_for [@group, @message], class:"new_message" do |f|
おそらくこちらのクラス適用されていないかと思います！
どちらにせよhash形式で書く場合は:のあとにスペース入れましょう！

2017-01-11 12:04 UTC, ryosukemotegi commented on app/views/messages/index.html.haml
> +      =form_for [@group, @message], class:"new_message" do |f|
ご指摘ありがとうございます、group.htmlコミット漏れでした！修正します。
messages/index.html.hamlのご指摘の内容承知しました！
確認とスペースの修正します。

2017-01-11 12:34 UTC, ryosukemotegi commented on app/models/group.rb
> +    messages.present? ? messages.last.body : "メッセージがありません"
アドバイスありがとうございます！！
なるほど、、、今回分から修正し、次回以降意識してみたいと思います！

2017-01-12 04:01 UTC, ryosukemotegi commented on app/views/groups/_group.html.haml
>    = link_to group_messages_path(group.id), class: 'chat-group__link' do
ご指摘ありがとうございます。
すみません、コミットが漏れていましたので改めて処理いたします！

2017-01-12 04:17 UTC, DaikiInaba commented on app/models/group.rb
> +  def view_message
メソッド名としてはlast_messageの方が適切かと思うのですがいかがでしょうか？

2017-01-12 04:17 UTC, DaikiInaba commented on app/views/groups/_group.html.haml
> +      = group.view_message
3行目は=を繋げて書いているのですが、こちらは改行した理由はありますでしょうか？

2017-01-12 04:17 UTC, DaikiInaba commented on app/views/messages/_message.html.haml
> +      =message.user.name
=のあとスペース入れるか入れないかは揃えましょう

2017-01-12 04:17 UTC, DaikiInaba commented on app/views/messages/index.html.haml
> +          =f.text_area :body, placeholder: "type a message", rows: "1", id:"message_body"
id:の後はスペース入れましょう

2017-01-12 04:18 UTC, DaikiInaba commented
コード自体は非常によく書けています！
ただ、書き方的なところで整頓されていないので、フォーマットを決めてそれに従って書くようにしましょう！

2017-01-12 05:37 UTC, ryosukemotegi commented on app/models/group.rb
> +  def view_message
ありがとうございます、last_messageの方が挙動の名前にふさわしいですね。
修正します！

2017-01-12 05:38 UTC, ryosukemotegi commented on app/views/groups/_group.html.haml
> +      = group.view_message
すみません、意図していない改行ですので修正します。

2017-01-12 05:43 UTC, ryosukemotegi commented on app/views/messages/_message.html.haml
> +      =message.user.name
ご指摘ありがとうございます、修正します！
意識できていなかったので気をつけて書くようにします。

2017-01-12 05:44 UTC, ryosukemotegi commented on app/views/messages/index.html.haml
> +          =f.text_area :body, placeholder: "type a message", rows: "1", id:"message_body"
承知しました、ありがとうございます。
こちらもスペースですね、修正します！

2017-01-12 05:51 UTC, ryosukemotegi commented
ありがとうございます！
レビューと修正を繰り返してだんだんコードがすっきりしていくのが楽しいです！
引き続きよろしくお願いいたします！
書き方についても意識して書けるようにしたいと思います！！

2017-01-12 06:22 UTC, tomoki0120 commented
LGTMです！
>書き方についても意識して書けるようにしたいと思います！！
素晴らしいです！

2017-01-12 06:24 UTC, ryosukemotegi commented
ありがとうございます！！　マージ後に次へ進みます！
レビューいただきましたメンターの皆さん、ありがとうございました！
引き続きご指導のほどよろしくお願いいたします。

2017-01-12 06:25 UTC, merged